INSERT INTO products (name, category) VALUES ('Смартфон Galaxy S24', 'Электроника');
INSERT INTO products (name, category) VALUES ('Ноутбук MacBook Air', 'Электроника');
INSERT INTO products (name, category) VALUES ('Наушники Sony WH-1000XM5', 'Электроника');
INSERT INTO products (name, category) VALUES ('Планшет iPad Pro', 'Электроника');
INSERT INTO products (name, category) VALUES ('Умные часы Apple Watch', 'Электроника');
INSERT INTO products (name, category) VALUES ('Фотоаппарат Canon EOS', 'Электроника');
INSERT INTO products (name, category) VALUES ('Игровая консоль PS5', 'Электроника');
INSERT INTO products (name, category) VALUES ('Монитор Dell 27"', 'Электроника');
INSERT INTO products (name, category) VALUES ('Клавиатура Mechanical', 'Электроника');
INSERT INTO products (name, category) VALUES ('Мышь Logitech MX', 'Электроника');
INSERT INTO products (name, category) VALUES ('Футболка белая базовая', 'Одежда');
INSERT INTO products (name, category) VALUES ('Джинсы Levi\'s 501', 'Одежда');
INSERT INTO products (name, category) VALUES ('Куртка зимняя North Face', 'Одежда');
INSERT INTO products (name, category) VALUES ('Кроссовки Nike Air Max', 'Одежда');
INSERT INTO products (name, category) VALUES ('Рубашка офисная', 'Одежда');
INSERT INTO products (name, category) VALUES ('Шорты спортивные', 'Одежда');
INSERT INTO products (name, category) VALUES ('Платье летнее', 'Одежда');
INSERT INTO products (name, category) VALUES ('Пиджак классический', 'Одежда');
INSERT INTO products (name, category) VALUES ('Носки хлопковые 5 пар', 'Одежда');
INSERT INTO products (name, category) VALUES ('Шапка шерстяная', 'Одежда');
INSERT INTO products (name, category) VALUES ('Молоко 3.2%', 'Продукты');
INSERT INTO products (name, category) VALUES ('Хлеб бородинский', 'Продукты');
INSERT INTO products (name, category) VALUES ('Яйца куриные С0', 'Продукты');
INSERT INTO products (name, category) VALUES ('Сыр Российский', 'Продукты');
INSERT INTO products (name, category) VALUES ('Кофе зерновой Arabica', 'Продукты');
INSERT INTO products (name, category) VALUES ('Чай черный зеленый', 'Продукты');
INSERT INTO products (name, category) VALUES ('Сахар песок 1кг', 'Продукты');
INSERT INTO products (name, category) VALUES ('Масло подсолнечное', 'Продукты');
INSERT INTO products (name, category) VALUES ('Макароны спагетти', 'Продукты');
INSERT INTO products (name, category) VALUES ('Шоколад молочный', 'Продукты');
INSERT INTO products (name, category) VALUES ('Война и мир Толстой', 'Книги');
INSERT INTO products (name, category) VALUES ('Преступление и наказание', 'Книги');
INSERT INTO products (name, category) VALUES ('Гарри Поттер том 1', 'Книги');
INSERT INTO products (name, category) VALUES ('Властелин колец', 'Книги');
INSERT INTO products (name, category) VALUES ('1984 Оруэлл', 'Книги');
INSERT INTO products (name, category) VALUES ('Мастер и Маргарита', 'Книги');
INSERT INTO products (name, category) VALUES ('Атлант расправил плечи', 'Книги');
INSERT INTO products (name, category) VALUES ('Sapiens Юваль Ной', 'Книги');
INSERT INTO products (name, category) VALUES ('Думай медленно решай быстро', 'Книги');
INSERT INTO products (name, category) VALUES ('Чистый код Мартин', 'Книги');
INSERT INTO products (name, category) VALUES ('Холодильник Samsung', 'Бытовая техника');
INSERT INTO products (name, category) VALUES ('Стиральная машина LG', 'Бытовая техника');
INSERT INTO products (name, category) VALUES ('Пылесос Dyson', 'Бытовая техника');
INSERT INTO products (name, category) VALUES ('Микроволновка Panasonic', 'Бытовая техника');
INSERT INTO products (name, category) VALUES ('Чайник электрический', 'Бытовая техника');
INSERT INTO products (name, category) VALUES ('Утюг Philips', 'Бытовая техника');
INSERT INTO products (name, category) VALUES ('Блендер Bosch', 'Бытовая техника');
INSERT INTO products (name, category) VALUES ('Тостер Redmond', 'Бытовая техника');
INSERT INTO products (name, category) VALUES ('Кофемашина DeLonghi', 'Бытовая техника');
INSERT INTO products (name, category) VALUES ('Кондиционер Ballu', 'Бытовая техника');
INSERT INTO products (name, category) VALUES ('Гантели разборные 10кг', 'Спорт');
INSERT INTO products (name, category) VALUES ('Коврик для йоги', 'Спорт');
INSERT INTO products (name, category) VALUES ('Велосипед горный', 'Спорт');
INSERT INTO products (name, category) VALUES ('Самокат электрический', 'Спорт');
INSERT INTO products (name, category) VALUES ('Мяч футбольный', 'Спорт');
INSERT INTO products (name, category) VALUES ('Ракетка теннисная', 'Спорт');
INSERT INTO products (name, category) VALUES ('Лыжи беговые', 'Спорт');
INSERT INTO products (name, category) VALUES ('Коньки фигурные', 'Спорт');
INSERT INTO products (name, category) VALUES ('Гиря 16кг', 'Спорт');
INSERT INTO products (name, category) VALUES ('Эспандер кистевой', 'Спорт');
INSERT INTO products (name, category) VALUES ('LEGO Technic', 'Игрушки');
INSERT INTO products (name, category) VALUES ('Кукла Barbie', 'Игрушки');
INSERT INTO products (name, category) VALUES ('Машинка Hot Wheels', 'Игрушки');
INSERT INTO products (name, category) VALUES ('Плюшевый мишка', 'Игрушки');
INSERT INTO products (name, category) VALUES ('Настольная игра Монополия', 'Игрушки');
INSERT INTO products (name, category) VALUES ('Пазл 1000 деталей', 'Игрушки');
INSERT INTO products (name, category) VALUES ('Конструктор Магнитный', 'Игрушки');
INSERT INTO products (name, category) VALUES ('Железная дорога', 'Игрушки');
INSERT INTO products (name, category) VALUES ('Робот трансформер', 'Игрушки');
INSERT INTO products (name, category) VALUES ('Набор для рисования', 'Игрушки');
INSERT INTO products (name, category) VALUES ('Диван угловой', 'Мебель');
INSERT INTO products (name, category) VALUES ('Стол письменный', 'Мебель');
INSERT INTO products (name, category) VALUES ('Стул офисный', 'Мебель');
INSERT INTO products (name, category) VALUES ('Шкаф купе', 'Мебель');
INSERT INTO products (name, category) VALUES ('Кровать двуспальная', 'Мебель');
INSERT INTO products (name, category) VALUES ('Комод белый', 'Мебель');
INSERT INTO products (name, category) VALUES ('Полка навесная', 'Мебель');
INSERT INTO products (name, category) VALUES ('Зеркало напольное', 'Мебель');
INSERT INTO products (name, category) VALUES ('Тумба прикроватная', 'Мебель');
INSERT INTO products (name, category) VALUES ('Стеллаж металлический', 'Мебель');
INSERT INTO products (name, category) VALUES ('Масло моторное 5W-30', 'Автозапчасти');
INSERT INTO products (name, category) VALUES ('Фильтр масляный', 'Автозапчасти');
INSERT INTO products (name, category) VALUES ('Свечи зажигания', 'Автозапчасти');
INSERT INTO products (name, category) VALUES ('Аккумулятор автомобильный', 'Автозапчасти');
INSERT INTO products (name, category) VALUES ('Колодки тормозные', 'Автозапчасти');
INSERT INTO products (name, category) VALUES ('Щетки стеклоочистителя', 'Автозапчасти');
INSERT INTO products (name, category) VALUES ('Антифриз красный', 'Автозапчасти');
INSERT INTO products (name, category) VALUES ('Ремень ГРМ', 'Автозапчасти');
INSERT INTO products (name, category) VALUES ('Лампа H7', 'Автозапчасти');
INSERT INTO products (name, category) VALUES ('Коврики в салон', 'Автозапчасти');
INSERT INTO products (name, category) VALUES ('Шампунь Head & Shoulders', 'Косметика');
INSERT INTO products (name, category) VALUES ('Крем для лица Nivea', 'Косметика');
INSERT INTO products (name, category) VALUES ('Тушь для ресниц', 'Косметика');
INSERT INTO products (name, category) VALUES ('Помада матовая', 'Косметика');
INSERT INTO products (name, category) VALUES ('Парфюм Chanel', 'Косметика');
INSERT INTO products (name, category) VALUES ('Гель для душа', 'Косметика');
INSERT INTO products (name, category) VALUES ('Зубная паста', 'Косметика');
INSERT INTO products (name, category) VALUES ('Дезодорант спрей', 'Косметика');
INSERT INTO products (name, category) VALUES ('Лак для ногтей', 'Косметика');
INSERT INTO products (name, category) VALUES ('Маска для волос', 'Косметика');

INSERT INTO prices (product_id, price, created_at) VALUES (1, 79990.00, '2026-04-20 10:00:00');
INSERT INTO prices (product_id, price, created_at) VALUES (1, 82500.00, DEFAULT);
INSERT INTO prices (product_id, price, created_at) VALUES (2, 115000.00, '2026-04-20 10:00:00');
INSERT INTO prices (product_id, price, created_at) VALUES (2, 119990.00, DEFAULT);
INSERT INTO prices (product_id, price, created_at) VALUES (3, 29990.00, '2026-04-20 10:00:00');
INSERT INTO prices (product_id, price, created_at) VALUES (3, 31500.00, DEFAULT);
INSERT INTO prices (product_id, price, created_at) VALUES (4, 85000.00, '2026-04-20 10:00:00');
INSERT INTO prices (product_id, price, created_at) VALUES (4, 89990.00, DEFAULT);
INSERT INTO prices (product_id, price, created_at) VALUES (5, 35000.00, '2026-04-20 10:00:00');
INSERT INTO prices (product_id, price, created_at) VALUES (5, 37990.00, DEFAULT);
INSERT INTO prices (product_id, price, created_at) VALUES (6, 65000.00, '2026-04-20 10:00:00');
INSERT INTO prices (product_id, price, created_at) VALUES (6, 68500.00, DEFAULT);
INSERT INTO prices (product_id, price, created_at) VALUES (7, 49990.00, '2026-04-20 10:00:00');
INSERT INTO prices (product_id, price, created_at) VALUES (7, 54990.00, DEFAULT);
INSERT INTO prices (product_id, price, created_at) VALUES (8, 25000.00, '2026-04-20 10:00:00');
INSERT INTO prices (product_id, price, created_at) VALUES (8, 27500.00, DEFAULT);
INSERT INTO prices (product_id, price, created_at) VALUES (9, 12000.00, '2026-04-20 10:00:00');
INSERT INTO prices (product_id, price, created_at) VALUES (9, 13500.00, DEFAULT);
INSERT INTO prices (product_id, price, created_at) VALUES (10, 8000.00, '2026-04-20 10:00:00');
INSERT INTO prices (product_id, price, created_at) VALUES (10, 8900.00, DEFAULT);
INSERT INTO prices (product_id, price, created_at) VALUES (11, 990.00, '2026-04-20 10:00:00');
INSERT INTO prices (product_id, price, created_at) VALUES (11, 1200.00, DEFAULT);
INSERT INTO prices (product_id, price, created_at) VALUES (12, 4500.00, '2026-04-20 10:00:00');
INSERT INTO prices (product_id, price, created_at) VALUES (12, 4990.00, DEFAULT);
INSERT INTO prices (product_id, price, created_at) VALUES (13, 15000.00, '2026-04-20 10:00:00');
INSERT INTO prices (product_id, price, created_at) VALUES (13, 16500.00, DEFAULT);
INSERT INTO prices (product_id, price, created_at) VALUES (14, 8900.00, '2026-04-20 10:00:00');
INSERT INTO prices (product_id, price, created_at) VALUES (14, 9500.00, DEFAULT);
INSERT INTO prices (product_id, price, created_at) VALUES (15, 2500.00, '2026-04-20 10:00:00');
INSERT INTO prices (product_id, price, created_at) VALUES (15, 2800.00, DEFAULT);
INSERT INTO prices (product_id, price, created_at) VALUES (16, 1500.00, '2026-04-20 10:00:00');
INSERT INTO prices (product_id, price, created_at) VALUES (16, 1700.00, DEFAULT);
INSERT INTO prices (product_id, price, created_at) VALUES (17, 3500.00, '2026-04-20 10:00:00');
INSERT INTO prices (product_id, price, created_at) VALUES (17, 3900.00, DEFAULT);
INSERT INTO prices (product_id, price, created_at) VALUES (18, 12000.00, '2026-04-20 10:00:00');
INSERT INTO prices (product_id, price, created_at) VALUES (18, 13500.00, DEFAULT);
INSERT INTO prices (product_id, price, created_at) VALUES (19, 450.00, '2026-04-20 10:00:00');
INSERT INTO prices (product_id, price, created_at) VALUES (19, 500.00, DEFAULT);
INSERT INTO prices (product_id, price, created_at) VALUES (20, 800.00, '2026-04-20 10:00:00');
INSERT INTO prices (product_id, price, created_at) VALUES (20, 950.00, DEFAULT);
INSERT INTO prices (product_id, price, created_at) VALUES (21, 85.00, '2026-04-20 10:00:00');
INSERT INTO prices (product_id, price, created_at) VALUES (21, 92.00, DEFAULT);
INSERT INTO prices (product_id, price, created_at) VALUES (22, 45.00, '2026-04-20 10:00:00');
INSERT INTO prices (product_id, price, created_at) VALUES (22, 50.00, DEFAULT);
INSERT INTO prices (product_id, price, created_at) VALUES (23, 120.00, '2026-04-20 10:00:00');
INSERT INTO prices (product_id, price, created_at) VALUES (23, 135.00, DEFAULT);
INSERT INTO prices (product_id, price, created_at) VALUES (24, 650.00, '2026-04-20 10:00:00');
INSERT INTO prices (product_id, price, created_at) VALUES (24, 720.00, DEFAULT);
INSERT INTO prices (product_id, price, created_at) VALUES (25, 1200.00, '2026-04-20 10:00:00');
INSERT INTO prices (product_id, price, created_at) VALUES (25, 1350.00, DEFAULT);
INSERT INTO prices (product_id, price, created_at) VALUES (26, 350.00, '2026-04-20 10:00:00');
INSERT INTO prices (product_id, price, created_at) VALUES (26, 390.00, DEFAULT);
INSERT INTO prices (product_id, price, created_at) VALUES (27, 60.00, '2026-04-20 10:00:00');
INSERT INTO prices (product_id, price, created_at) VALUES (27, 65.00, DEFAULT);
INSERT INTO prices (product_id, price, created_at) VALUES (28, 110.00, '2026-04-20 10:00:00');
INSERT INTO prices (product_id, price, created_at) VALUES (28, 125.00, DEFAULT);
INSERT INTO prices (product_id, price, created_at) VALUES (29, 80.00, '2026-04-20 10:00:00');
INSERT INTO prices (product_id, price, created_at) VALUES (29, 90.00, DEFAULT);
INSERT INTO prices (product_id, price, created_at) VALUES (30, 150.00, '2026-04-20 10:00:00');
INSERT INTO prices (product_id, price, created_at) VALUES (30, 170.00, DEFAULT);
INSERT INTO prices (product_id, price, created_at) VALUES (31, 800.00, '2026-04-20 10:00:00');
INSERT INTO prices (product_id, price, created_at) VALUES (31, 850.00, DEFAULT);
INSERT INTO prices (product_id, price, created_at) VALUES (32, 450.00, '2026-04-20 10:00:00');
INSERT INTO prices (product_id, price, created_at) VALUES (32, 490.00, DEFAULT);
INSERT INTO prices (product_id, price, created_at) VALUES (33, 600.00, '2026-04-20 10:00:00');
INSERT INTO prices (product_id, price, created_at) VALUES (33, 650.00, DEFAULT);
INSERT INTO prices (product_id, price, created_at) VALUES (34, 2500.00, '2026-04-20 10:00:00');
INSERT INTO prices (product_id, price, created_at) VALUES (34, 2800.00, DEFAULT);
INSERT INTO prices (product_id, price, created_at) VALUES (35, 500.00, '2026-04-20 10:00:00');
INSERT INTO prices (product_id, price, created_at) VALUES (35, 550.00, DEFAULT);
INSERT INTO prices (product_id, price, created_at) VALUES (36, 700.00, '2026-04-20 10:00:00');
INSERT INTO prices (product_id, price, created_at) VALUES (36, 750.00, DEFAULT);
INSERT INTO prices (product_id, price, created_at) VALUES (37, 900.00, '2026-04-20 10:00:00');
INSERT INTO prices (product_id, price, created_at) VALUES (37, 950.00, DEFAULT);
INSERT INTO prices (product_id, price, created_at) VALUES (38, 1100.00, '2026-04-20 10:00:00');
INSERT INTO prices (product_id, price, created_at) VALUES (38, 1200.00, DEFAULT);
INSERT INTO prices (product_id, price, created_at) VALUES (39, 800.00, '2026-04-20 10:00:00');
INSERT INTO prices (product_id, price, created_at) VALUES (39, 850.00, DEFAULT);
INSERT INTO prices (product_id, price, created_at) VALUES (40, 1500.00, '2026-04-20 10:00:00');
INSERT INTO prices (product_id, price, created_at) VALUES (40, 1600.00, DEFAULT);
INSERT INTO prices (product_id, price, created_at) VALUES (41, 45000.00, '2026-04-20 10:00:00');
INSERT INTO prices (product_id, price, created_at) VALUES (41, 48000.00, DEFAULT);
INSERT INTO prices (product_id, price, created_at) VALUES (42, 35000.00, '2026-04-20 10:00:00');
INSERT INTO prices (product_id, price, created_at) VALUES (42, 37500.00, DEFAULT);
INSERT INTO prices (product_id, price, created_at) VALUES (43, 40000.00, '2026-04-20 10:00:00');
INSERT INTO prices (product_id, price, created_at) VALUES (43, 42000.00, DEFAULT);
INSERT INTO prices (product_id, price, created_at) VALUES (44, 8000.00, '2026-04-20 10:00:00');
INSERT INTO prices (product_id, price, created_at) VALUES (44, 8500.00, DEFAULT);
INSERT INTO prices (product_id, price, created_at) VALUES (45, 2500.00, '2026-04-20 10:00:00');
INSERT INTO prices (product_id, price, created_at) VALUES (45, 2800.00, DEFAULT);
INSERT INTO prices (product_id, price, created_at) VALUES (46, 3500.00, '2026-04-20 10:00:00');
INSERT INTO prices (product_id, price, created_at) VALUES (46, 3900.00, DEFAULT);
INSERT INTO prices (product_id, price, created_at) VALUES (47, 5000.00, '2026-04-20 10:00:00');
INSERT INTO prices (product_id, price, created_at) VALUES (47, 5500.00, DEFAULT);
INSERT INTO prices (product_id, price, created_at) VALUES (48, 2000.00, '2026-04-20 10:00:00');
INSERT INTO prices (product_id, price, created_at) VALUES (48, 2200.00, DEFAULT);
INSERT INTO prices (product_id, price, created_at) VALUES (49, 25000.00, '2026-04-20 10:00:00');
INSERT INTO prices (product_id, price, created_at) VALUES (49, 27000.00, DEFAULT);
INSERT INTO prices (product_id, price, created_at) VALUES (50, 30000.00, '2026-04-20 10:00:00');
INSERT INTO prices (product_id, price, created_at) VALUES (50, 32000.00, DEFAULT);
INSERT INTO prices (product_id, price, created_at) VALUES (51, 3500.00, '2026-04-20 10:00:00');
INSERT INTO prices (product_id, price, created_at) VALUES (51, 3800.00, DEFAULT);
INSERT INTO prices (product_id, price, created_at) VALUES (52, 1500.00, '2026-04-20 10:00:00');
INSERT INTO prices (product_id, price, created_at) VALUES (52, 1700.00, DEFAULT);
INSERT INTO prices (product_id, price, created_at) VALUES (53, 25000.00, '2026-04-20 10:00:00');
INSERT INTO prices (product_id, price, created_at) VALUES (53, 27500.00, DEFAULT);
INSERT INTO prices (product_id, price, created_at) VALUES (54, 35000.00, '2026-04-20 10:00:00');
INSERT INTO prices (product_id, price, created_at) VALUES (54, 38000.00, DEFAULT);
INSERT INTO prices (product_id, price, created_at) VALUES (55, 2000.00, '2026-04-20 10:00:00');
INSERT INTO prices (product_id, price, created_at) VALUES (55, 2200.00, DEFAULT);
INSERT INTO prices (product_id, price, created_at) VALUES (56, 5000.00, '2026-04-20 10:00:00');
INSERT INTO prices (product_id, price, created_at) VALUES (56, 5500.00, DEFAULT);
INSERT INTO prices (product_id, price, created_at) VALUES (57, 15000.00, '2026-04-20 10:00:00');
INSERT INTO prices (product_id, price, created_at) VALUES (57, 16500.00, DEFAULT);
INSERT INTO prices (product_id, price, created_at) VALUES (58, 8000.00, '2026-04-20 10:00:00');
INSERT INTO prices (product_id, price, created_at) VALUES (58, 8500.00, DEFAULT);
INSERT INTO prices (product_id, price, created_at) VALUES (59, 2500.00, '2026-04-20 10:00:00');
INSERT INTO prices (product_id, price, created_at) VALUES (59, 2800.00, DEFAULT);
INSERT INTO prices (product_id, price, created_at) VALUES (60, 500.00, '2026-04-20 10:00:00');
INSERT INTO prices (product_id, price, created_at) VALUES (60, 600.00, DEFAULT);
INSERT INTO prices (product_id, price, created_at) VALUES (61, 4500.00, '2026-04-20 10:00:00');
INSERT INTO prices (product_id, price, created_at) VALUES (61, 4900.00, DEFAULT);
INSERT INTO prices (product_id, price, created_at) VALUES (62, 2500.00, '2026-04-20 10:00:00');
INSERT INTO prices (product_id, price, created_at) VALUES (62, 2800.00, DEFAULT);
INSERT INTO prices (product_id, price, created_at) VALUES (63, 800.00, '2026-04-20 10:00:00');
INSERT INTO prices (product_id, price, created_at) VALUES (63, 900.00, DEFAULT);
INSERT INTO prices (product_id, price, created_at) VALUES (64, 1500.00, '2026-04-20 10:00:00');
INSERT INTO prices (product_id, price, created_at) VALUES (64, 1700.00, DEFAULT);
INSERT INTO prices (product_id, price, created_at) VALUES (65, 3000.00, '2026-04-20 10:00:00');
INSERT INTO prices (product_id, price, created_at) VALUES (65, 3300.00, DEFAULT);
INSERT INTO prices (product_id, price, created_at) VALUES (66, 1200.00, '2026-04-20 10:00:00');
INSERT INTO prices (product_id, price, created_at) VALUES (66, 1350.00, DEFAULT);
INSERT INTO prices (product_id, price, created_at) VALUES (67, 2000.00, '2026-04-20 10:00:00');
INSERT INTO prices (product_id, price, created_at) VALUES (67, 2200.00, DEFAULT);
INSERT INTO prices (product_id, price, created_at) VALUES (68, 5000.00, '2026-04-20 10:00:00');
INSERT INTO prices (product_id, price, created_at) VALUES (68, 5500.00, DEFAULT);
INSERT INTO prices (product_id, price, created_at) VALUES (69, 3500.00, '2026-04-20 10:00:00');
INSERT INTO prices (product_id, price, created_at) VALUES (69, 3800.00, DEFAULT);
INSERT INTO prices (product_id, price, created_at) VALUES (70, 1000.00, '2026-04-20 10:00:00');
INSERT INTO prices (product_id, price, created_at) VALUES (70, 1100.00, DEFAULT);
INSERT INTO prices (product_id, price, created_at) VALUES (71, 45000.00, '2026-04-20 10:00:00');
INSERT INTO prices (product_id, price, created_at) VALUES (71, 48000.00, DEFAULT);
INSERT INTO prices (product_id, price, created_at) VALUES (72, 15000.00, '2026-04-20 10:00:00');
INSERT INTO prices (product_id, price, created_at) VALUES (72, 16500.00, DEFAULT);
INSERT INTO prices (product_id, price, created_at) VALUES (73, 8000.00, '2026-04-20 10:00:00');
INSERT INTO prices (product_id, price, created_at) VALUES (73, 8500.00, DEFAULT);
INSERT INTO prices (product_id, price, created_at) VALUES (74, 25000.00, '2026-04-20 10:00:00');
INSERT INTO prices (product_id, price, created_at) VALUES (74, 27000.00, DEFAULT);
INSERT INTO prices (product_id, price, created_at) VALUES (75, 35000.00, '2026-04-20 10:00:00');
INSERT INTO prices (product_id, price, created_at) VALUES (75, 38000.00, DEFAULT);
INSERT INTO prices (product_id, price, created_at) VALUES (76, 12000.00, '2026-04-20 10:00:00');
INSERT INTO prices (product_id, price, created_at) VALUES (76, 13000.00, DEFAULT);
INSERT INTO prices (product_id, price, created_at) VALUES (77, 3000.00, '2026-04-20 10:00:00');
INSERT INTO prices (product_id, price, created_at) VALUES (77, 3300.00, DEFAULT);
INSERT INTO prices (product_id, price, created_at) VALUES (78, 5000.00, '2026-04-20 10:00:00');
INSERT INTO prices (product_id, price, created_at) VALUES (78, 5500.00, DEFAULT);
INSERT INTO prices (product_id, price, created_at) VALUES (79, 4000.00, '2026-04-20 10:00:00');
INSERT INTO prices (product_id, price, created_at) VALUES (79, 4300.00, DEFAULT);
INSERT INTO prices (product_id, price, created_at) VALUES (80, 7000.00, '2026-04-20 10:00:00');
INSERT INTO prices (product_id, price, created_at) VALUES (80, 7500.00, DEFAULT);
INSERT INTO prices (product_id, price, created_at) VALUES (81, 2500.00, '2026-04-20 10:00:00');
INSERT INTO prices (product_id, price, created_at) VALUES (81, 2700.00, DEFAULT);
INSERT INTO prices (product_id, price, created_at) VALUES (82, 500.00, '2026-04-20 10:00:00');
INSERT INTO prices (product_id, price, created_at) VALUES (82, 550.00, DEFAULT);
INSERT INTO prices (product_id, price, created_at) VALUES (83, 1200.00, '2026-04-20 10:00:00');
INSERT INTO prices (product_id, price, created_at) VALUES (83, 1300.00, DEFAULT);
INSERT INTO prices (product_id, price, created_at) VALUES (84, 8000.00, '2026-04-20 10:00:00');
INSERT INTO prices (product_id, price, created_at) VALUES (84, 8500.00, DEFAULT);
INSERT INTO prices (product_id, price, created_at) VALUES (85, 3500.00, '2026-04-20 10:00:00');
INSERT INTO prices (product_id, price, created_at) VALUES (85, 3800.00, DEFAULT);
INSERT INTO prices (product_id, price, created_at) VALUES (86, 1500.00, '2026-04-20 10:00:00');
INSERT INTO prices (product_id, price, created_at) VALUES (86, 1600.00, DEFAULT);
INSERT INTO prices (product_id, price, created_at) VALUES (87, 2000.00, '2026-04-20 10:00:00');
INSERT INTO prices (product_id, price, created_at) VALUES (87, 2200.00, DEFAULT);
INSERT INTO prices (product_id, price, created_at) VALUES (88, 800.00, '2026-04-20 10:00:00');
INSERT INTO prices (product_id, price, created_at) VALUES (88, 900.00, DEFAULT);
INSERT INTO prices (product_id, price, created_at) VALUES (89, 300.00, '2026-04-20 10:00:00');
INSERT INTO prices (product_id, price, created_at) VALUES (89, 350.00, DEFAULT);
INSERT INTO prices (product_id, price, created_at) VALUES (90, 1500.00, '2026-04-20 10:00:00');
INSERT INTO prices (product_id, price, created_at) VALUES (90, 1700.00, DEFAULT);
INSERT INTO prices (product_id, price, created_at) VALUES (91, 450.00, '2026-04-20 10:00:00');
INSERT INTO prices (product_id, price, created_at) VALUES (91, 500.00, DEFAULT);
INSERT INTO prices (product_id, price, created_at) VALUES (92, 1200.00, '2026-04-20 10:00:00');
INSERT INTO prices (product_id, price, created_at) VALUES (92, 1350.00, DEFAULT);
INSERT INTO prices (product_id, price, created_at) VALUES (93, 800.00, '2026-04-20 10:00:00');
INSERT INTO prices (product_id, price, created_at) VALUES (93, 900.00, DEFAULT);
INSERT INTO prices (product_id, price, created_at) VALUES (94, 5000.00, '2026-04-20 10:00:00');
INSERT INTO prices (product_id, price, created_at) VALUES (94, 5500.00, DEFAULT);
INSERT INTO prices (product_id, price, created_at) VALUES (95, 1500.00, '2026-04-20 10:00:00');
INSERT INTO prices (product_id, price, created_at) VALUES (95, 1700.00, DEFAULT);
INSERT INTO prices (product_id, price, created_at) VALUES (96, 600.00, '2026-04-20 10:00:00');
INSERT INTO prices (product_id, price, created_at) VALUES (96, 700.00, DEFAULT);
INSERT INTO prices (product_id, price, created_at) VALUES (97, 300.00, '2026-04-20 10:00:00');
INSERT INTO prices (product_id, price, created_at) VALUES (97, 350.00, DEFAULT);
INSERT INTO prices (product_id, price, created_at) VALUES (98, 400.00, '2026-04-20 10:00:00');
INSERT INTO prices (product_id, price, created_at) VALUES (98, 450.00, DEFAULT);
INSERT INTO prices (product_id, price, created_at) VALUES (99, 700.00, '2026-04-20 10:00:00');
INSERT INTO prices (product_id, price, created_at) VALUES (99, 800.00, DEFAULT);
INSERT INTO prices (product_id, price, created_at) VALUES (100, 550.00, '2026-04-20 10:00:00');
INSERT INTO prices (product_id, price, created_at) VALUES (100, 600.00, DEFAULT);

-- Поставщики для первых 10 товаров (электроника) - по 3 шт
INSERT INTO suppliers (name, product_id) VALUES ('ООО "ТехноМир"', 1);
INSERT INTO suppliers (name, product_id) VALUES ('ИП Сидоров', 1);
INSERT INTO suppliers (name, product_id) VALUES ('ЗАО "Гаджеты"', 1);
INSERT INTO suppliers (name, product_id) VALUES ('ООО "ТехноМир"', 2);
INSERT INTO suppliers (name, product_id) VALUES ('Apple Russia', 2);
INSERT INTO suppliers (name, product_id) VALUES ('ООО "Компьютерный мир"', 2);
INSERT INTO suppliers (name, product_id) VALUES ('ООО "АудиоСтор"', 3);
INSERT INTO suppliers (name, product_id) VALUES ('Sony Direct', 3);
INSERT INTO suppliers (name, product_id) VALUES ('ИП Петров', 3);
INSERT INTO suppliers (name, product_id) VALUES ('ООО "Планшеты.ру"', 4);
INSERT INTO suppliers (name, product_id) VALUES ('Apple Russia', 4);
INSERT INTO suppliers (name, product_id) VALUES ('ЗАО "Дигитал"', 4);
INSERT INTO suppliers (name, product_id) VALUES ('ООО "Часы24"', 5);
INSERT INTO suppliers (name, product_id) VALUES ('Apple Russia', 5);
INSERT INTO suppliers (name, product_id) VALUES ('ИП Иванов', 5);
INSERT INTO suppliers (name, product_id) VALUES ('ООО "ФотоПро"', 6);
INSERT INTO suppliers (name, product_id) VALUES ('Canon Store', 6);
INSERT INTO suppliers (name, product_id) VALUES ('ЗАО "Объектив"', 6);
INSERT INTO suppliers (name, product_id) VALUES ('ООО "ГеймЛэнд"', 7);
INSERT INTO suppliers (name, product_id) VALUES ('Sony Direct', 7);
INSERT INTO suppliers (name, product_id) VALUES ('ИП Смирнов', 7);
INSERT INTO suppliers (name, product_id) VALUES ('ООО "Мониторы+"', 8);
INSERT INTO suppliers (name, product_id) VALUES ('Dell Official', 8);
INSERT INTO suppliers (name, product_id) VALUES ('ЗАО "Экран"', 8);
INSERT INTO suppliers (name, product_id) VALUES ('ООО "КлаваМышь"', 9);
INSERT INTO suppliers (name, product_id) VALUES ('ИП Кузнецов', 9);
INSERT INTO suppliers (name, product_id) VALUES ('ЗАО "Периферия"', 9);
INSERT INTO suppliers (name, product_id) VALUES ('ООО "Логитек Рус"', 10);
INSERT INTO suppliers (name, product_id) VALUES ('ИП Попов', 10);
INSERT INTO suppliers (name, product_id) VALUES ('ЗАО "Девайсы"', 10);

-- Поставщики для остальных товаров (11-100) - по 1-2 шт
INSERT INTO suppliers (name, product_id) VALUES ('ООО "ОдеждаОпт"', 11);
INSERT INTO suppliers (name, product_id) VALUES ('Текстиль Групп', 12);
INSERT INTO suppliers (name, product_id) VALUES ('ООО "Стиль"', 12);
INSERT INTO suppliers (name, product_id) VALUES ('ЗАО "Зима-Лето"', 13);
INSERT INTO suppliers (name, product_id) VALUES ('ИП Васильев', 14);
INSERT INTO suppliers (name, product_id) VALUES ('ООО "Кроссовки"', 14);
INSERT INTO suppliers (name, product_id) VALUES ('Рубашкин Дом', 15);
INSERT INTO suppliers (name, product_id) VALUES ('СпортМастер Опт', 16);
INSERT INTO suppliers (name, product_id) VALUES ('ООО "Мода"', 17);
INSERT INTO suppliers (name, product_id) VALUES ('ИП Морозов', 18);
INSERT INTO suppliers (name, product_id) VALUES ('ЗАО "Носки-Сетки"', 19);
INSERT INTO suppliers (name, product_id) VALUES ('ООО "Шапка"', 20);
INSERT INTO suppliers (name, product_id) VALUES ('Молочная Река', 21);
INSERT INTO suppliers (name, product_id) VALUES ('Хлебозавод №5', 22);
INSERT INTO suppliers (name, product_id) VALUES ('Птицефабрика', 23);
INSERT INTO suppliers (name, product_id) VALUES ('СырПром', 24);
INSERT INTO suppliers (name, product_id) VALUES ('КофеИмпорт', 25);
INSERT INTO suppliers (name, product_id) VALUES ('ЧайТрейд', 26);
INSERT INTO suppliers (name, product_id) VALUES ('СахарРус', 27);
INSERT INTO suppliers (name, product_id) VALUES ('МаслоЗавод', 28);
INSERT INTO suppliers (name, product_id) VALUES ('МакаронФабрика', 29);
INSERT INTO suppliers (name, product_id) VALUES ('ШоколадМир', 30);
INSERT INTO suppliers (name, product_id) VALUES ('Книжный Дом', 31);
INSERT INTO suppliers (name, product_id) VALUES ('ЛитРес Опт', 32);
INSERT INTO suppliers (name, product_id) VALUES ('Буквоед', 33);
INSERT INTO suppliers (name, product_id) VALUES ('ФэнтезиМир', 34);
INSERT INTO suppliers (name, product_id) VALUES ('КлассикаКниг', 35);
INSERT INTO suppliers (name, product_id) VALUES ('Букинист', 36);
INSERT INTO suppliers (name, product_id) VALUES ('БизнесКниги', 37);
INSERT INTO suppliers (name, product_id) VALUES ('НаучПоп', 38);
INSERT INTO suppliers (name, product_id) VALUES ('ПсихологияПресс', 39);
INSERT INTO suppliers (name, product_id) VALUES ('ITBooks', 40);
INSERT INTO suppliers (name, product_id) VALUES ('БытТехникаОпт', 41);
INSERT INTO suppliers (name, product_id) VALUES ('Samsung Rus', 41);
INSERT INTO suppliers (name, product_id) VALUES ('LG Electronics', 42);
INSERT INTO suppliers (name, product_id) VALUES ('ТехноШок', 43);
INSERT INTO suppliers (name, product_id) VALUES ('Panasonic Store', 44);
INSERT INTO suppliers (name, product_id) VALUES ('Чайник-Варик', 45);
INSERT INTO suppliers (name, product_id) VALUES ('УтюгСервис', 46);
INSERT INTO suppliers (name, product_id) VALUES ('Bosch Home', 47);
INSERT INTO suppliers (name, product_id) VALUES ('Redmond Club', 48);
INSERT INTO suppliers (name, product_id) VALUES ('DeLongi Shop', 49);
INSERT INTO suppliers (name, product_id) VALUES ('КлиматКонтроль', 50);
INSERT INTO suppliers (name, product_id) VALUES ('СпортИнвентарь', 51);
INSERT INTO suppliers (name, product_id) VALUES ('ФитнесОпт', 52);
INSERT INTO suppliers (name, product_id) VALUES ('ВелоМир', 53);
INSERT INTO suppliers (name, product_id) VALUES ('СамокатРу', 54);
INSERT INTO suppliers (name, product_id) VALUES ('МячМаркет', 55);
INSERT INTO suppliers (name, product_id) VALUES ('ТеннисПро', 56);
INSERT INTO suppliers (name, product_id) VALUES ('ЛыжняРус', 57);
INSERT INTO suppliers (name, product_id) VALUES ('КонькиБега', 58);
INSERT INTO suppliers (name, product_id) VALUES ('ЖелезоСпорт', 59);
INSERT INTO suppliers (name, product_id) VALUES ('РезинаТяга', 60);
INSERT INTO suppliers (name, product_id) VALUES ('LEGO Store', 61);
INSERT INTO suppliers (name, product_id) VALUES ('ИгрушкиДетям', 62);
INSERT INTO suppliers (name, product_id) VALUES ('МашинкиОпт', 63);
INSERT INTO suppliers (name, product_id) VALUES ('МишкаПлюш', 64);
INSERT INTO suppliers (name, product_id) VALUES ('НастолкиРу', 65);
INSERT INTO suppliers (name, product_id) VALUES ('ПазлМастер', 66);
INSERT INTO suppliers (name, product_id) VALUES ('МагнитКонструктор', 67);
INSERT INTO suppliers (name, product_id) VALUES ('ЖелДорИгра', 68);
INSERT INTO suppliers (name, product_id) VALUES ('РоботТранс', 69);
INSERT INTO suppliers (name, product_id) VALUES ('АртНабор', 70);
INSERT INTO suppliers (name, product_id) VALUES ('МебельШик', 71);
INSERT INTO suppliers (name, product_id) VALUES ('ДиванОпт', 71);
INSERT INTO suppliers (name, product_id) VALUES ('СтолСтул', 72);
INSERT INTO suppliers (name, product_id) VALUES ('ОфисМебель', 73);
INSERT INTO suppliers (name, product_id) VALUES ('ШкафСервис', 74);
INSERT INTO suppliers (name, product_id) VALUES ('КроватьМечты', 75);
INSERT INTO suppliers (name, product_id) VALUES ('КомодДом', 76);
INSERT INTO suppliers (name, product_id) VALUES ('ПолкаСтена', 77);
INSERT INTO suppliers (name, product_id) VALUES ('ЗеркалоСвет', 78);
INSERT INTO suppliers (name, product_id) VALUES ('ТумбаНочь', 79);
INSERT INTO suppliers (name, product_id) VALUES ('СтеллажМеталл', 80);
INSERT INTO suppliers (name, product_id) VALUES ('АвтоМасло', 81);
INSERT INTO suppliers (name, product_id) VALUES ('ФильтрАвто', 82);
INSERT INTO suppliers (name, product_id) VALUES ('СвечиЗажиг', 83);
INSERT INTO suppliers (name, product_id) VALUES ('АккумуляторРус', 84);
INSERT INTO suppliers (name, product_id) VALUES ('ТормозаОпт', 85);
INSERT INTO suppliers (name, product_id) VALUES ('ЩеткиДвор', 86);
INSERT INTO suppliers (name, product_id) VALUES ('АнтифризЦвет', 87);
INSERT INTO suppliers (name, product_id) VALUES ('РеменьГРМ', 88);
INSERT INTO suppliers (name, product_id) VALUES ('ЛампаСвет', 89);
INSERT INTO suppliers (name, product_id) VALUES ('КоврикАвто', 90);
INSERT INTO suppliers (name, product_id) VALUES ('ШампуньОпт', 91);
INSERT INTO suppliers (name, product_id) VALUES ('КремЛицо', 92);
INSERT INTO suppliers (name, product_id) VALUES ('ТушьРесницы', 93);
INSERT INTO suppliers (name, product_id) VALUES ('ПомадаСтик', 94);
INSERT INTO suppliers (name, product_id) VALUES ('ПарфюмЛюкс', 95);
INSERT INTO suppliers (name, product_id) VALUES ('ГельДуш', 96);
INSERT INTO suppliers (name, product_id) VALUES ('ПастаЗуб', 97);
INSERT INTO suppliers (name, product_id) VALUES ('ДезодорантСпрей', 98);
INSERT INTO suppliers (name, product_id) VALUES ('ЛакНогти', 99);
INSERT INTO suppliers (name, product_id) VALUES ('МаскаВолос', 100);